- hosts: jen
  become: yes
  become_user: root
  become_method: sudo

  tasks:
     - name: Install wget
       apt:
       name: wget

     - name: Install jdk 8 java
       apt: 
       name: openjdk-8-jdk

     - name: Install jdk 8 jre
       apt:
       name: openjdk-8-jre

     - name: Descargar llave
       command: wget -q -O - https://pkg.jenkins.io/debian-stable/jenkins.io.key | sudo apt-key add -
       
     - name: Obtener repositorio Jenkins
       command: sh -c 'echo deb http://pkg.jenkins-ci.org/debian-stable binary/ > /etc/apt/sources.list.d/jenkins.list'
       
     - name: Install Jenkins
       apt:
       name: jenkins